eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8765
spring:
  application:
    name: application-gateway
  cloud:
    config:
      enabled: false